const seq = [
    {
      name: "Suraya Namascar A",
      asana: [
        ["Samasthiti", "Attention"],
        ["Urdva Hastasana", "Raised Hands Pose"],
        ["Uttanassana", "Forward Fold Pose"],
        ["Ardha Uttanassana", "Half-lift Pose"],
        ["Chataranga Dandasana", "Four-pointed Staff Pose"],
        ["Urdva Mukha Svanasana", "Upward Facing Dog Pose"],
        ["Adho Mukha Svanasana", "Upward Facing Dog Pose"],
        ["Ardha Uttanassana", "Half-lift Pose"],
        ["Uttanassana", "Forward Fold Pose"],
        ["Urdva Hastasana", "Raised Hands Pose"],
        ["Samasthiti", "Attention"]
      ]
    },
    {
      name: "Suraya Namascar B",
      asana: [
        ["Samasthiti", "Attention"],
        ["Utkatasana", "Intense Pose"],
        ["Uttanassana", "Forward Fold Pose"],
        ["Ardha Uttanassana", "Half-lift Pose"],
        ["Chataranga Dandasana", "Four-pointed Staff Pose"],
        ["Urdva Mukha Svanasana", "Upward Facing Dog Pose"],
        ["Adho Mukha Svanasana", "Upward Facing Dog Pose", "https://en.wikipedia.org/wiki/Adho_mukha_%C5%9Bv%C4%81n%C4%81sana"],
        ["Three Point Adho Mukha Svanasana", "Three Point Upward Facing Dog Pose"],
        ["Virabhadrasana A", "Warior 1"],
        ["Three Point Adho Mukha Svanasana", "Three Point Upward Facing Dog Pose"],
        ["Three Point Chataranga Dandasana", "Three Point Four-pointed Staff Pose"],
        ["Urdva Mukha Svanasana", "Upward Facing Dog Pose"],
        ["Ardha Uttanassana", "Half-lift Pose"],
        ["Uttanassana", "Forward Fold Pose"],
        ["Utkatasana", "Intense Pose"],
        ["Samasthiti", "Attention"]
      ]
    },
    {
      name: "Standing Series",
      asana: [
        ["Utkatasana", "Intense Pose"],
        ["Parivrita Utkatasana", "Intense Pose"],
        ["Pandangusithasana", "Folded Toe Grab Pose"],
        ["Utkatasana", "Intense Pose"],
        ["Parivrita Utkatasana", "Intense Pose"],
        ["Padahastasana", "Hands to Feet Pose"],
        ["Bakasana", "Crow Pose"],
        ["Chataranga Dandasana", "Four-pointed Staff Pose"],
        ["Urdva Mukha Svanasana", "Upward Facing Dog Pose"],
        ["Adho Mukha Svanasana", "Upward Facing Dog Pose", "https://en.wikipedia.org/wiki/Adho_mukha_%C5%9Bv%C4%81n%C4%81sana"],
        ["Yogi Crunch", "Yogi Crunch"],
        ["Alanasana", "High Lunge"],
        ["Urdva Prasarita Ekapadasana", "Upward Folded One-footed-pose"],
        ["Prasarita Padotanasana C", "Folded Head Intense Pose C"],
        ["Prasarita Padotanasana D", "Folded Head Intense Pose D"],
        ["Trikonasana", "Triangle Pose"],
        ["Parivrita Trikonasana", "Folded Triangle Pose"],
        ["Balasana", "Child's Pose"],
        ["Adho Mukha Svanasana", "Upward Facing Dog Pose", "https://en.wikipedia.org/wiki/Adho_mukha_%C5%9Bv%C4%81n%C4%81sana"],
        ["Twisting Crunch", "Twisting Crunch"],
        ["Vasisthasana", "Extended Side Angle"],
        ["Virabhadrasana D", "Humble Warior"],
        ["Virabhadrasana B", "Warior 2"],
        ["Utthita Parsvakonasana", "Extended Side Angle"],
        ["Anjaneyasana", "Cresent Lunge"],
        ["Ekapada Rajakapotasana", "One Legged King Pidgeon"],
        ["Ardha Chandrasana", "Half Moon"],
        ["Virabhadrasana C", "Warior 3"],
        ["Guradasana", "Eagle Pose"]
      ],
    },
    {
      name: "Seated Series",
      asana: [
        ["Paschim Attanasana A", "Forward Bend 1"],
        ["Paschim Attanasana D", "Forward Bend 2"],
        ["Purvatanasana", "Reverse Plank"],
        ["Janu Sirsana A", "Head to Lnee Pose"],
        ["Marichyasana A", "Sage's Pose 1"],
        ["Marichyasana C", "Sage's Pose 2"],
        ["Navasana", "Boat Pose"],
        ["Badhakonaasana", "Bound Angle Pose"],
        ["Shalabhasana A", "Locust Pose 1"],
        ["Shalabhasana B", "Locust Pose 2"],
        ["Pincha Mayurasana", "Feathered Peacock Pose"],
        ["Setu Bhandasana", "Bound Bridge Pose"],
        ["Urdva Danurasana", "Upward Bow Pose"],
        ["Salamba Sarvangasana", "Supported Shoulderstand Pose"],
        ["Halasana", "Plow Pose"],
        ["Karnapidasana", "Deaf Pose"],
        ["Uthana Padasana", "Intense Leg Pose"],
        ["Badha Padmasana", "Bound Lotus Pose"],
        ["Yoga Mudra", "Yogi Hand Sign"],
        ["Utplutih", "Intense Raise"],
        ["Svanasana", "Corpse Pose"],
        ["Om Om Om", "Tripple Primordial Cosmic Vibration"]
      ]
    }
  ]
  const all = [
        ["Samasthiti", "Attention"],
        ["Urdva Hastasana", "Raised Hands Pose"],
        ["Uttanassana", "Forward Fold Pose"],
        ["Ardha Uttanassana", "Half-lift Pose"],
        ["Chataranga Dandasana", "Four-pointed Staff Pose"],
        ["Urdva Mukha Svanasana", "Upward Facing Dog Pose"],
        ["Adho Mukha Svanasana", "Upward Facing Dog Pose"],
        ["Ardha Uttanassana", "Half-lift Pose"],
        ["Uttanassana", "Forward Fold Pose"],
        ["Urdva Hastasana", "Raised Hands Pose"],
        ["Samasthiti", "Attention"],
    ["Utkatasana", "Intense Pose"],
    ["Uttanassana", "Forward Fold Pose"],
    ["Ardha Uttanassana", "Half-lift Pose"],
    ["Chataranga Dandasana", "Four-pointed Staff Pose"],
    ["Urdva Mukha Svanasana", "Upward Facing Dog Pose"],
    ["Adho Mukha Svanasana", "Upward Facing Dog Pose", "https://en.wikipedia.org/wiki/Adho_mukha_%C5%9Bv%C4%81n%C4%81sana"],
    ["Three Point Adho Mukha Svanasana", "Three Point Upward Facing Dog Pose"],
    ["Virabhadrasana A", "Warior 1"],
    ["Three Point Adho Mukha Svanasana", "Three Point Upward Facing Dog Pose"],
    ["Three Point Chataranga Dandasana", "Three Point Four-pointed Staff Pose"],
    ["Urdva Mukha Svanasana", "Upward Facing Dog Pose"],
    ["Ardha Uttanassana", "Half-lift Pose"],
    ["Uttanassana", "Forward Fold Pose"],
    ["Utkatasana", "Intense Pose"],
    ["Samasthiti", "Attention"],
    ["Utkatasana", "Intense Pose"],
    ["Parivrita Utkatasana", "Intense Pose"],
    ["Pandangusithasana", "Folded Toe Grab Pose"],
    ["Utkatasana", "Intense Pose"],
    ["Parivrita Utkatasana", "Intense Pose"],
    ["Padahastasana", "Hands to Feet Pose"],
    ["Bakasana", "Crow Pose"],
    ["Chataranga Dandasana", "Four-pointed Staff Pose"],
    ["Urdva Mukha Svanasana", "Upward Facing Dog Pose"],
    ["Adho Mukha Svanasana", "Upward Facing Dog Pose", "https://en.wikipedia.org/wiki/Adho_mukha_%C5%9Bv%C4%81n%C4%81sana"],
    ["Yogi Crunch", "Yogi Crunch"],
    ["Alanasana", "High Lunge"],
    ["Urdva Prasarita Ekapadasana", "Upward Folded One-footed-pose"],
    ["Prasarita Padotanasana C", "Folded Head Intense Pose C"],
    ["Prasarita Padotanasana D", "Folded Head Intense Pose D"],
    ["Trikonasana", "Triangle Pose"],
    ["Parivrita Trikonasana", "Folded Triangle Pose"],
    ["Balasana", "Child's Pose"],
    ["Adho Mukha Svanasana", "Upward Facing Dog Pose", "https://en.wikipedia.org/wiki/Adho_mukha_%C5%9Bv%C4%81n%C4%81sana"],
    ["Twisting Crunch", "Twisting Crunch"],
    ["Vasisthasana", "Extended Side Angle"],
    ["Virabhadrasana D", "Humble Warior"],
    ["Virabhadrasana B", "Warior 2"],
    ["Utthita Parsvakonasana", "Extended Side Angle"],
    ["Anjaneyasana", "Cresent Lunge"],
    ["Ekapada Rajakapotasana", "One Legged King Pidgeon"],
    ["Ardha Chandrasana", "Half Moon"],
    ["Virabhadrasana C", "Warior 3"],
    ["Guradasana", "Eagle Pose"],
        ["Paschim Attanasana A", "Forward Bend 1"],
        ["Paschim Attanasana D", "Forward Bend 2"],
        ["Purvatanasana", "Reverse Plank"],
        ["Janu Sirsana A", "Head to Lnee Pose"],
        ["Marichyasana A", "Sage's Pose 1"],
        ["Marichyasana C", "Sage's Pose 2"],
        ["Navasana", "Boat Pose"],
        ["Badhakonaasana", "Bound Angle Pose"],
        ["Shalabhasana A", "Locust Pose 1"],
        ["Shalabhasana B", "Locust Pose 2"],
        ["Pincha Mayurasana", "Feathered Peacock Pose"],
        ["Setu Bhandasana", "Bound Bridge Pose"],
        ["Urdva Danurasana", "Upward Bow Pose"],
        ["Salamba Sarvangasana", "Supported Shoulderstand Pose"],
        ["Halasana", "Plow Pose"],
        ["Karnapidasana", "Deaf Pose"],
        ["Uthana Padasana", "Intense Leg Pose"],
        ["Badha Padmasana", "Bound Lotus Pose"],
        ["Yoga Mudra", "Yogi Hand Sign"],
        ["Utplutih", "Intense Raise"],
        ["Svanasana", "Corpse Pose"],
        ["Om Om Om", "Tripple Primordial Cosmic Vibration"]
  ] 